# Generated by Django 5.0.6 on 2024-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'administrator'), ('Tutor', 'tutor'), ('Student', 'student')], max_length=100),
        ),
    ]
