# Generated by Django 5.0.6 on 2024-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
    ]
