# Generated by Django 5.0.6 on 2024-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(default=[], to='skillshare_api.review'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(default=[], to='skillshare_api.enrollment'),
        ),
    ]
