# Generated by Django 5.0.6 on 2024-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare_api', '0003_course_current_students_alter_course_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
